# 多环境配置，此配置暂时没有启用
# SimNow 7x24环境（16:00到第二天08:59可用）
SimNow_7x24:
  BrokerID: "9999"
  TdFrontAddress: "tcp://182.254.243.31:40001"  # 交易前置
  MdFrontAddress: "tcp://182.254.243.31:40011"  # 行情前置
  AppID: "simnow_client_test"
  AuthCode: "0000000000000000"
  ProductInfo: ""

# SimNow电信环境
SimNow:
  BrokerID: "9999"
  TdFrontAddress: "tcp://182.254.243.31:30001"
  MdFrontAddress: "tcp://182.254.243.31:30012"
  AppID: "simnow_client_test"
  AuthCode: "0000000000000000"
  ProductInfo: ""

HuaAn:
  BrokerID: "9999"
  TdFrontAddress: "tcp://180.166.37.178:41207"
  MdFrontAddress: "tcp://180.166.37.178:41215"
  AppID: "simnow_client_test"
  AuthCode: "0000000000000000"
  ProductInfo: ""

# 当前使用的环境
Enable_MD: SimNow_7x24
Enable_TD: SimNow_7x24